### ISSUE TITLE
Unable to pick target and focus cast name position due to screen stuck.

### ISSUE THREAD

**Issue by Revontuletwow** [TheTrueIndolent/voodoo-casting-bar#1]
The target and focus frame is still to big to pick the cast bar name position, it gets stuck on the screen.

 Also i would love to have in target and focus spell school color, would be it possible ?

Big thank you !

![options picture](https://github.com/user-attachments/assets/a5a0db10-f161-4639-a4c0-0c6927688baa)

**Comment by Good-Mojo-Studio** [comment]
Hello and thanks for the comment!
Sorry for the delayed answer, I am new here! :)
VCB 1.50 fixes this issue!
